plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE
remote_theme: pages-themes/primer@v0.6.0
title: DuckStack VM
description: DuckStack Bytecode Virtual Machine for duckyPad duckyScript binaries
permissions:
  id-token: write
  pages: write
  contents: read